package de.ep.astralrelics.relic;

public enum RelicType {
    ECHO_RELICT,
    GALE_RELICT,
    CHRONO_RELICT,
    GRAVITY_RELICT,
    FROST_RELICT,
    PHOENIX_RELICT,
    ABYSS_RELICT,
    SHADOW_RELICT,
    BERSERKER_RELICT,
    MIRROR_RELICT,
    NATURE_RELICT,
    MAGNET_RELICT
}